id: I44BBE767
ocr_import_info:
  timestamp: '2023-09-26T03:44:04.210704+00:00'
  batch_id: batch-0ffc
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Dharma Kyab
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-09-26 04:38:02.383454+00:00
last_modified: 2023-09-26 04:38:02.383460+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W1NLM1105
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1NLM1105
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བསྟན་བཅོས་ཆེན་པོ་དབུ་མ་ལ་འཇུག་པའི་རྣམ་བཤད་དགོངས་པ་རབ་གསལ།
  languages:
  - bo
  author: ཙོང་ཁ་པ་བློ་བཟང་གྲགས་པ།
statistics:
  ocr_word_mean_confidence_index: 0.9454021205912013
  ocr_word_median_confidence_index: 0.9915808
bases:
  I1NLM1105_001:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1NLM1105_001
      total_pages: 526
      volume_number: 1
      volume_pages_bdrc_intro: 0
    order: 1
    base_file: I1NLM1105_001.txt
    statistics:
      ocr_word_median_confidence_index: 0.9915808
      ocr_word_mean_confidence_index: 0.9454021205912013
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
